const MOVIES = {
    REQUEST_DATA: "REQUEST_DATA",
    LOAD_SUCCESS: "LOAD_SUCCESS",
    LOAD_ERROR: "LOAD_ERROR",
    SEARCH: "SEARCH",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_ERROR: "SEARCH_ERROR",
    SAVE_MOVIE: "SAVE_MOVIE",
    UPDATE_MOVIELIST: "UPDATE_MOVIELIST"
};

export default MOVIES;