const MOVIES = {
    REQUEST_DATA: "REQUEST_DATA",
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_ERROR: "REQUEST_ERROR",
    SEARCH_DATA: "SEARCH_DATA",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_ERROR: "SEARCH_ERROR",
    SAVE_MOVIE: "SAVE_MOVIE",
    UPDATE_MOVIELIST: "UPDATE_MOVIELIST"
};

export default MOVIES;
